### ISSUE TITLE
Test whether a custom nextjs image loader for our ipfs images improve page load

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1053]
[Image optimization](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports#image-optimization) via custom loader that fetches from ipfs could be a quick win for improved page load

**Comment by calebjacob** [comment]
Hey @charleslavon, I'm currently spending time doing research to gain a better understanding of IPFS as a whole. Then hopefully I'll end up with some recommendations for how we can improve IPFS image loading.

**Comment by calebjacob** [comment]
Hey @charleslavon, after a bunch of research and chatting with @mpeterdev, I've discovered the following. I pre-apologize for the wall of text, but I think all of this context is useful info.

Using `next/image` sounds perfect for our needs if you read their documentation on caching: https://nextjs.org/docs/pages/api-reference/components/image#caching-behavior

> Images are optimized dynamically upon request and stored in the <distDir>/cache/images directory. The optimized image file will be served for subsequent requests until the expiration is reached.

This would be great! It would allow cached images to load faster versus having to always load from `https://ipfs.near.social/ipfs/...`.

So I started to dig in to how the implementation would work. Let's start at ground zero - loading an image the simple way with a regular `<img>` tag (what we currently do today in BOS components):

```
<img src="https://ipfs.near.social/ipfs/bafkreib6sp7aoovferwg4zfvekhxxmp6hdp4u7f2bgxupebntrfgrmjhbe" />
```

<img width="1317" alt="Screen Shot 2024-03-28 at 2 00 07 PM" src="https://github.com/near/near-discovery/assets/1475067/1fa7e55e-1254-4be3-a1b3-fc5751eefda9">

Great, so we know we can load the image like we always have. But there's a catch, and you can see the issue if you visit the file directly by URL in your browser (you will see a 403 error): https://ipfs.near.social/ipfs/bafkreib6sp7aoovferwg4zfvekhxxmp6hdp4u7f2bgxupebntrfgrmjhbe

My best guess is the IPFS gateway `ipfs.near.social` has a whitelist based on the `Referer` header. When visiting a URL directly in your browser, no `Referer` header is sent, so that's why see a 403. We'll run into this same problem as we continue on below with `next/image`.

The first thing we need to do is configure our `next.config.js` file according to this documentation: https://nextjs.org/docs/pages/api-reference/components/image#configuration-options

We end up with this:

```js
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'ipfs.near.social',
        pathname: '/ipfs/*',
      },
    ],
  },
  // ...
}
```

Now we can attempt to use `next/image` in a test on a Next JS Page like so (same IPFS resource/image as used above):

```jsx
import Image from 'next/image';

<Image
        src="https://ipfs.near.social/ipfs/bafkreib6sp7aoovferwg4zfvekhxxmp6hdp4u7f2bgxupebntrfgrmjhbe"
        width={500}
        height={500}
        alt="My Image"
      />
```

When you load the test page, you'll notice a broken image link. First, look at the output HTML for the image:

```
<img alt="My Image" loading="lazy" decoding="async" data-nimg="1" style="" srcset="/_next/image?url=https%3A%2F%2Fipfs.near.social%2Fipfs%2Fbafkreib6sp7aoovferwg4zfvekhxxmp6hdp4u7f2bgxupebntrfgrmjhbe&amp;w=640&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fipfs.near.social%2Fipfs%2Fbafkreib6sp7aoovferwg4zfvekhxxmp6hdp4u7f2bgxupebntrfgrmjhbe&amp;w=1080&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fipfs.near.social%2Fipfs%2Fbafkreib6sp7aoovferwg4zfvekhxxmp6hdp4u7f2bgxupebntrfgrmjhbe&amp;w=1080&amp;q=75" width="500" height="500">
```

There's a lot going on, but these are the important parts:

- Next JS inlines the size we passed in onto the `<img>` tag: `width="500" height="500"` 
- Since we told Next that the image is 500px wide, it gives the browser a couple of options for different sizes (based on pixel density of the device) to load in the `srcset` attribute - based on the closest matching [device size](https://nextjs.org/docs/pages/api-reference/components/image#devicesizes)
- It also gives a default fallback `src` attribute for older browsers that don't support `srcset` (Only IE 11 and lower need the fallback).
- Since we didn't specify a `quality` value, it defaults to `q=75`.

So at this point the image is broken. Let's visit one of these URL's in our browser: http://localhost:3000/_next/image?url=https%3A%2F%2Fipfs.near.social%2Fipfs%2Fbafkreib6sp7aoovferwg4zfvekhxxmp6hdp4u7f2bgxupebntrfgrmjhbe&w=1080&q=75

We see the following error message from Next:

> "url" parameter is valid but upstream response is invalid

We are now back to the 403 IPFS gateway response issue we saw in the beginning. Next JS does not pass along a `Referer` header when loading the remote image - and you can't customize the headers in any way. I did a ton of googling and eventually found a page where Next themselves call out setting `Headers` as unsupported: https://nextjs.org/docs/pages/building-your-application/deploying/static-exports#unsupported-features

### Next Steps

1. The IPFS gateway currently throws a 403 when Next tries to reach out to load the image. There's nothing on the Next JS side that we can do to fix this. We'd need to look into collaborating with the maintainer of `ipfs.social.near` to loosen the whitelist rules (or maybe remove the restrictions entirely for fetching images).

2. We need to decide if Next's enforcement of passing a `width` and `height` is a dealbreaker or not. It will lead to a lot of refactoring needing to be done to make sure we pass in correct values for ALL the images we render. The `next/image` component does support an alternative [fill](https://nextjs.org/docs/pages/api-reference/components/image#fill) prop instead of passing width and height, but this means you still need to set up a wrapping element with the proper styles to size and fit the image properly for its aspect ratio.

3. If we go this route, we'll need to pass through a custom `<Image />` component to the VM just like we do for `Link` and make sure we implement a default fallback inside the VM codebase (for other gateways that haven't implement `Image` yet):

```js
initNear({
  customElements: {
    Image // Pass in `next/image` component directly
});
```

4. Before we do much else, we should verify how much faster Vercel's caching strategy is compared to loading an image directly through the existing IPFS gateway. I'd imagine the IPFS gateway already has a pretty decent caching layer on top of it. I'm going to set up a test for this that should give us a benchmark. I'll add a new comment with that test once I get that published.

**Comment by calebjacob** [comment]
@charleslavon I opened up a PR to give us some real test benchmark results: https://github.com/near/near-discovery/pull/1096

I left my conclusion at the end of the description - let me know what you think!

**Comment by calebjacob** [comment]
With our [benchmark](https://github.com/near/near-discovery/pull/1096) tests, it's pretty clear that `next/image` will give us a large performance improvement. We've create a new ticket to tackle this effort: https://github.com/near/near-discovery/issues/1097
