### ISSUE TITLE
Pinned Apps (New Navigation)

### ISSUE THREAD

**Issue by calebjacob** [near/near-discovery#1056]
https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=399%3A14302&mode=dev

Build out the UI required to support `Pinned Apps` in our new layout:

<img width="423" alt="Screen Shot 2024-03-11 at 3 18 12 PM" src="https://github.com/near/near-discovery/assets/1475067/6927700b-eccc-4b52-9e44-8ccdd0839b87">

Questions:

- How will users pin apps? We'll need to build out that flow and decide how to store that data. Will probably need to fetch it from a Query API indexer.  @calebjacob @vanessadespain do we need to build this as a new ability, or should we reuse the existing ability to Star components?

**Comment by vanessadespain** [comment]
Hey @calebjacob @charleslavon here are a few thoughts and considerations to get us going. I'd love your thoughts and I can adjust the user journey as needed and provide designs to support. 

**User journey:** 
From the Near Gateway logged-in users have the ability to pin apps to their side bar navigation. Apps can be pinned from an App Detail Page. Pinned apps are managed from the user’s profile with the ability to unpin apps. A user's most recently visited pinned app will be positioned at the top of the Pinned Apps list, both in their profile and on the side bar. 

**Considerations:** 
On marketing pages the current path to view applications is the [Near Catalog](https://near.org/applications). The Near Catalog is managed by ecosystem contributors. We would need to collaborate with them to enable this new pinning feature. Currently the Catalog's star/”[bookmarking](https://near.org/nearcatalog.near/widget/Index?bookmark=lfg)” system seems to be browser based instead of based on login. If we add the pinning function to the Near Catalog we should also add the same functionality to the [Apps tab](https://near.org/near/widget/ComponentsPage?tab=apps) on the components page to create a consistent experience. 

**Discussion: How to proceed** 
My assessment of the Near Catalog is that it's a great entry point for visitors of the marketing site to see the many apps created on the Near Ecosystem, and bookmark favorites from the vast catalog as they browse. I think the catalog as it is currently designed is less ideal for a logged-in user experience.

For the purpose of our gateway I think a more robust experience, like the App Detail page created on the Components tab is more relevant to a logged-in user with the ability to fork, discuss, pin, etc. 

My initial preference is to build our pinning feature within the context of the pagoda-built App Detail pages and to push users to discover apps to pin via the Apps tab on the components page. We could offer the Near Catalog team to also utilize the feature but it would require integrating with the logged-in experience — is that feasible? Would it be worth having a meeting/discussion with that team to assess their interest?

In terms of leveraging the star feature and duplicating it for pinning — I imagine this could be helpful but I defer to you two on how best to technically implement. I think the UI for pinning will be very similar to starring with the addition that a user would immediately see their nav bar updated with the newly pinned app.

**Comment by calebjacob** [comment]
Hey @vanessadespain, good thoughts on the Near Catalog page. For the scope of this ticket and for the sake of getting an MVP out the door, my recommendation would be to:

1. Update our `AppDetails` page to allow users to pin/unpin a specific app. Technically, this will work exactly the same as star/unstar.
2. Update our `ProfilePage` to add a `Pinned` tab that behaves just like the `Stars` tab where it lists cards for every app you've pinned. You could click on a card to see the `AppDetails` page to then unpin if you'd like.
3. Update our new sidebar layout to list the pinned apps of the currently signed in user.

How does that sound?

We can then have a follow up discussion or tickets to figure out what needs to happen next. This way we're not blocked on the external Near Catalog page and we can follow up with that team when we have time.

**Comment by vanessadespain** [comment]
That sounds ideal to me! Thank you @calebjacob

**Comment by charleslavon** [comment]
Thanks both for moving this forward. 

It sounds like we are effectively renaming `Starred` to `Pinned` and will need to discuss/plan how to transition to Pinned instead of Starred across our gateway pages and the Near Catalog. Is that accurate @calebjacob ?

**Comment by calebjacob** [comment]
@charleslavon No problem! So `Pinned` would be a new feature - not a replacement for `Starred`. You'll most likely only want to pin 1 or 2 apps - where as it's nice to give a star to any component you think is cool.

Does that sound right @vanessadespain?

**Comment by vanessadespain** [comment]
+1 adding pinning and not replacing starring. 

To be seen how many apps a user wants to pin but I also assume it’s far less than starred apps.
