### ISSUE TITLE
Logged-in Home page

### ISSUE THREAD

**Issue by vanessadespain** [near/near-discovery#1071]
# New Homepage for Logged-in Experience

Rather than taking a user directly to a feed experience, we want to set the stage for being able to orient the user to the features of the gateway. For this first iteration we'll use static cards that introduce building, trending apps, and learning. 

[Figma Designs](https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=902%3A22197&mode=design&t=wMRhE1UovKLYukwq-1)
![image](https://github.com/near/near-discovery/assets/8346374/ee489574-a5e5-4199-8cfb-cdfbfbe0a81d)

### Building: 
Create a Project -> Jutsu.ai's [new project page](https://app.jutsu.ai/)
Fork a Project -> [NEAR components page](https://near.org/components)

### Trending Apps: 
This will pull the top 6 trending apps from the [NEAR Catalog](https://near.org/nearcatalog.near/widget/Index?cat=trending). Explore link should go to NEAR Catalog home page (near.org/applications)
FYI in the future we hope this to become more dynamic and show apps a user has favorited or interacted with.

### Learning: 
Documentation -> [NEAR's documentation homepage](https://docs.near.org/)
Lessons -> [Jutsu.ai's learn page](https://app.jutsu.ai/learn)

**Comment by vanessadespain** [comment]
Also FYI I'll be OOO Mon-Weds (3/18-20) but Charles has best knowledge of the intended function for this page.

**Comment by s-n-park** [comment]
Would it be possible to also surface components and NFTs on profile pages since roughly 25%/18% of visitors that get to the profile page click on these sections?

![image](https://github.com/near/near-discovery/assets/146785798/275ed756-04ad-4a23-98de-6d5a6b6b8b03)

[Analysis](https://docs.google.com/presentation/d/1sanOPAIiVC6dAhBq4lT91GDImK1hAwa3kDxByaY6a3w/edit#slide=id.g28f0a44f540_0_122)
