### ISSUE TITLE
Refactor ipfs images with Next/Images for all NearOrg.* components 

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1097]
**Request*
Based on [these image optimization findings](https://github.com/near/near-discovery/pull/1096), this ticket aims to improve the initial page load of the NearOrg marketing pages,  by refactoring the current ipfs images in use on all NearOrg.* pages (except NearOrg.Notifications.*) to use the NextJS/Image pattern with [priority=true for largest images](https://nextjs.org/docs/pages/api-reference/components/image#priority).

**Comment by calebjacob** [comment]
For more context on next steps, feel free to check out my comment here: https://github.com/near/near-discovery/issues/1053#issuecomment-2026101921

Specifically, we now need to focus on these next steps:

1. The IPFS gateway currently throws a 403 when Next tries to reach out to load the image. There's nothing on the Next JS side that we can do to fix this. We'd need to look into collaborating with the maintainer of `ipfs.social.near` to loosen the whitelist rules (or maybe remove the restrictions entirely for fetching images).

2. We'll need to pass through a custom <Image /> component to the VM just like we do for Link and make sure we implement a default fallback inside the VM codebase (for other gateways that haven't implemented `Image` yet - otherwise those gateways will throw an error trying to render an `Image` component that doesn't exist):

```js
initNear({
  customElements: {
    Image // Pass in `next/image` component directly
});
```

**Comment by charleslavon** [comment]
hey @calebjacob I think we can avoid #1 by limiting this refactor to the marketing pages only (the logged out view), and by replacing it's ipfs images with locally stored PNG files. Does that sounds right?

**Comment by calebjacob** [comment]
Sure, that's a good point. Probably doesn't make sense to involve IPFS at all for the marketing pages at this point. We can just host public images on our current gateway server in `public/images/...` for anything that needs a performance boost.

**Comment by calebjacob** [comment]
Closing this for now as per our discussion @charleslavon - feel free to re-open or modify as you see fit.
