### ISSUE TITLE
How might we update the gateway such that it supports both RoC and nearsocial/VM?

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1130]
Must we await the completion of [361](https://github.com/near/bos-web-engine/issues/361) or can we import RoC into the gateway via gitsubmodule or another way?

**Comment by calebjacob** [comment]
Good question. We certainly could attempt to use a git submodule for the interim in `near-discovery`. Normally I'd push back on any use of a git submodule, but it could be okay in this case since we could create a rule for our team that we never ever commit a change in the submodule - it's essentially read-only.

One alternative idea would be to start up a new Next JS app in the RoC monorepo (maybe `apps/backwards-compatible-gateway`). That has its own set of drawbacks I'm afraid.

**Comment by calebjacob** [comment]
I'll give this a shot first using a git submodule to link `react-on-chain` inside `near-discovery`. One challenge we'll need to think through once `react-on-chain` is published to NPM is overall loading performance. The RoC and VM engines are both super heavy to load on the client side - it would be ideal if an end user only has to load one or the other and not both when visiting a page.

**Comment by calebjacob** [comment]
After a few hours of experimenting with using a git submodule to include `react-on-chain` inside `near-discovery`, it seems like it's probably not worth continuing to pursue due to all the issues I've been running into. It's a real challenge getting the submodule's monorepo to build and properly link as a dependency in the parent project without any runtime errors.

I'd suggest working on other priorities while we wait for RoC to be published to NPM. I'm going to close this for now @charleslavon - feel free to re-open or adjust as you see fit.
