### ISSUE TITLE
Surface near.org Support Contact Channel Findability 

### ISSUE THREAD

**Issue by reiokam** [near/near-discovery#1210]
**Is your feature request related to a problem? Please describe.**
Yes. The removal of the link to submit help requests on the contact-us UI has caused a significant decrease in support ticket volume.  We are now receiving approximately half the number of support tickets compared to previous months.  (fyi @gagdiez)

**Describe the solution you'd like**

1.  Reintroduce the "Resolve an issue" contact card on the dev.near.org/contact-us UI. 

**Additional context**
The decrease in support tickets indicates that users are struggling to find the necessary help resources. Reintroducing a prominent Contact Us button would improve user experience and ensure that users can easily reach out for assistance when needed. The design of the button could be refined in collaboration with the design team to ensure it complements the overall website aesthetics. A Google search for "NEAR Support" does not easily lead users to a clear way to find help or submit inquiries.

**Comment by reiokam** [comment]
@vanessadespain , would you mind sanity checking this? Would love your thoughts or if there might be any additional information I can provide that would be helpful?

**Comment by vanessadespain** [comment]
@reiokam Thanks for tagging me on this! 

I see that dev.near's support page has changed content and removed our two pathways for 1. the Help Center and 2. the Support form to be able to log tickets. 

**P0 Change:** 
I think we should at least replace the content card that currently has "Chat Support" which duplicates content from the main card. Replace this content with the pathway to submit a support ticket to Zendesk — seen in the original design under the headline "Resolve an issue"

**P1 Change:** 
The Contact link on the main near.org was changed to the dev.near support page. Rei and I can work on updating the content from the previous contact/support pages (links below) so that Near can have its own top level pathway for support and contact. We'll work with Laura to help see how this should be implemented.  
https://pages.near.org/about/contact-us/
https://pages.near.org/developers/get-help/

**Here's the original design we launched with:** 
![image](https://github.com/near/near-discovery/assets/8346374/31282211-d892-4aaf-8e20-cb7a76fbe986)

**Comment by charleslavon** [comment]
@vanessadespain @reiokam I've updated the description to call-out the single change that should be made here - re-adding the Resolve an Issue card.   Regarding the below idea, there is no one on the NF side that is making updates to these legacy wordpress pages, so focus on informing Laura to influence her designs for the new near.org vs trying to increase our use of these old wordpress pages.

> P1 Change:
The Contact link on the main near.org was changed to the dev.near support page. Rei and I can work on updating the content from the previous contact/support pages (links below) so that Near can have its own top level pathway for support and contact. We'll work with Laura to help see how this should be implemented.
https://pages.near.org/about/contact-us/
https://pages.near.org/developers/get-help/

**Comment by vanessadespain** [comment]
@charleslavon Thanks for working on this for us! 
cc @gagdiez in case he had made these content changes. 

In the P0 I had mentioned removing the current copy about "Chat support" since it duplicates the copy in the main card. Can we do that? If necessary, we can update the copy in the main card to include "chat with our developers on Telegram and Discord". On a side note, is it an accurate promise that a user will be able to get live support from our devs?

Suggestion: Remove the copy shown here
![image](https://github.com/near/near-discovery/assets/8346374/ae916f47-201b-45b3-9ef5-e44ab0674b0e)

Suggestion: Small copy tweak. Instead of Thursdays - 11hs & 18hs. Change to Thursdays: 11hs & 18hs

Suggestion: Add back the subcopy under Resolve an issue headline, "Get in touch with our customer care team"
![image](https://github.com/near/near-discovery/assets/8346374/105837c6-4ad0-4658-b615-5676d7d8f925)

Thanks for your callout on the P1 — Rei is working on a content outline and we'll share that work with Laura for the next iteration of near.org

**Comment by reiokam** [comment]
Thanks @charleslavon, @gagdiez, and @vanessadespain for your help with this! 

Putting my working doc outline (https://docs.google.com/document/d/1ZaRfpG_jA5JQ7OSyaYkkWTdx_lgqkz-35Rwdj7-r3bA/edit#heading=h.8m7powo250re) here for reference.
