### ISSUE TITLE
Developer Survey issues

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1258]
1. The 'Next' button becomes hidden and there is no way to vertically scroll down.  https://www.loom.com/share/ebf6cac41b17444999977aa950ecedfd
2. Trigger hiding the 'Gleap' support affordance on display of the developer survey, and show it upon closing/submitting the developer survey.
3. If you haven't already, get feedback from Jo & Spencer on whether they suggest any changes to the structure of the event payload to better facilitate the types of queries we'll likely want to make.
4. Rather than add a unique attribute for each question on a wizard screen `question, question2, etc` , consider storing the questions of form pages with multiple questions into an array. That way we one can iterate through the array of questions `questions[0], questions[1]` etc.  instead of needing to know how many questions to expect in each form 
<img width="782" alt="Screen Shot 2024-07-19 at 9 15 20 AM" src="https://github.com/user-attachments/assets/21fc698b-ed31-4143-bb98-12d75917f80a">

**Comment by charleslavon** [comment]
@jackson-harris-iii please prioritize this so we can fix before the next push to main.

**Comment by charleslavon** [comment]
@s-n-park  could you take a look at the incoming data on Near Discovery Stage and provide any feedback?

**Comment by jackson-harris-iii** [comment]
@charleslavon In regards to #4 

> Rather than add a unique attribute for each question on a wizard screen question, question2, etc , consider storing the questions of form pages with multiple questions into an array. That way we one can iterate through the array of questions questions[0], questions[1] etc. instead of needing to know how many questions to expect in each form

I thought quite a bit about this and the implementation came down to a few things in my mind. There is only the one question that has "two questions" and each question set is pretty different (text, check boxes, selecting bubbles, etc) some have subtitles while some don't which in turn make displaying the questions, subtitles, and possible answers slightly different in each page so the pages themselves handle these unique properties at the expense of having the true questions/subtext being sent over. I think that it is totally possible to hoist the questions, subtext, etc into the object, but in order to handle to difference making more generic pages I felt would've taken quite a bit longer but with no impact to the UX and hopefully minimal issues for the data team.

**Comment by s-n-park** [comment]
@charleslavon, @jackson-harris-iii - I took a look here and unfortunately I didn't realize that Rudderstack restricts usage of more [complex schema](https://www.rudderstack.com/docs/api/data-catalog-api/json-schema/#restricted-keyword-structures).

So the response object is unfortunately not getting parsed out. I think our 2 options here are:
1. Add a function to unnest properties fields in the existing [Rudderstack transformation](https://app.rudderstack.com/transformations). I don't have edit access to transformation but could add that in

2. Breakout logging so response field is an array instead of nested schema.

**Comment by charleslavon** [comment]
Thanks @s-n-park, could you elaborate on what you mean by option #2?

**Comment by s-n-park** [comment]
Sure, as an [example](https://pagodaplatform.slack.com/archives/C0559BC3WBZ/p1721168833582619?thread_ts=1720845623.481609&cid=C0559BC3WBZ) that Jackson had shared, we'd want to remove the keys within response subfield and flatten that field to only an array.

**Example Question 1**
_Current Schema_
`"properties": { `
`    "questionNumber": "1",`
`     "response": { `
`         "interests": ["Docs", "Evaluating tech"],    `
`},`

_Flattened Schema_
`"properties": { `
`    "questionNumber": "1",`
`    "response": ["Docs", "Evaluating tech"],    `
`},

**Example Question 2**
_Current Schema_
`"properties": { `
`    "questionNumber": "2",`
`    "response": { `
`         "selectedUserTypes": [ "Full-stack developer", "Back-end developer"],    `
`},`

_Flattened Schema_
`"properties": { `
`    "questionNumber": "1",`
`     "response": ["Full-stack developer", Back-end developer],    `
`},`

**Comment by jackson-harris-iii** [comment]
Had a chat with @s-n-park seen below. TLDR; changed payload to use snake case, append 'response_' to responses and flattened them in the payload instead of having a nested object.
<img width="1224" alt="Screenshot 2024-07-23 at 11 14 31 AM" src="https://github.com/user-attachments/assets/0e9f3c85-f4bd-4f12-9ad1-21d509f8f39e">
