### ISSUE TITLE
P1 [NEARCON] Update Terms of Use

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#525]
Make sure the Terms of Service is up to date and make it available at a new URL: near.org/terms. Following the formatting of our [privacy policy page](https://near.org/privacy)

Here is our current version: https://docs.google.com/document/d/1L-t_1KtrFRI2Zgm9mfq8pnZ3Z9RIrcJ6zledwFRbygk/edit

- [ ] Updating the Terms of Use that users agree to when signing into near.org for the first time;
- [ ] Adding a new route to our viewer /terms that will display the terms of use
- [ ] Remove "alpha.near.org" and "during alpha testing" from the ToS modal

@shelegdmitriy I've added the last two bullet points above
<img width="645" alt="Screen Shot 2023-10-30 at 5 59 46 PM" src="https://github.com/near/near-discovery/assets/1915116/c938ad9c-0990-4f11-b246-4200ce1bcf5b">

**Comment by tidus974** [comment]
#cookie-banner-and-policy-implementation channel for more details

**Comment by charleslavon** [comment]
@tidus974 the google doc includes this text at the top `Privacy Policy found here https://near.org/privacy/ when signed in for first time` Do we want to display this in the UI as well?

**Comment by tidus974** [comment]
Apologies @charleslavon, I put that line for reference, please don't include it. 
Also, the document is a copy of what I saw on our website but our ToS is actually hosted in IPFS via Infura’s pinning service. If we could get that version it might be better (Michael Peter knows more if needed)

**Comment by tidus974** [comment]
Actually I just checked the ToS version in production and it's the same to the google doc so you can use that one. Thanks

**Comment by shelegdmitriy** [comment]
I don't have an access to that google doc @tidus974 and I sent you request for it. [near.org/privacy](https://near.org/privacy) are showing a content from https://pages.near.org/privacy using `IframeResizer` component which means I can't really make changes there.

cc @charleslavon

**Comment by shelegdmitriy** [comment]
Also I can't find #cookie-banner-and-policy-implementation channel

**Comment by charleslavon** [comment]
hey @shelegdmitriy  sorry for the ambiguity in the notes here. This ticket is about accomplishing two things 

1. Updating the Terms of Use that users agree to when signing into near.org for the first time
2. adding a new route to our viewer `/terms` that will display the terms of use

@mpeterdev could you share some guidance on how we can update the on-chain stored terms of use?

**Comment by tidus974** [comment]
I just gave you access to the Gdoc @shelegdmitriy

**Comment by mpeterdev** [comment]
updating these documents is performed by uploading a new version to IPFS then modifying the `TosContent` component to point to the new CIDs. A few notes on doing this:
- the `TosContent` component has been compied to the `near` account and exists in our `near-discovery-components` repo, however we are not yet pointing to that version because switching to using that instead of the `adminalpha.near` instance would have trigger a global re-acceptance prompt even though the content is the same. This is because acceptance is tied to a specific version of TosContent as opposed to CIDs. By tying acceptance to a `TosContent` version, we are essentially creating agreement versions which span multiple documents, as opposed to tracking agreement to each document individually
  - this is a great opportunity to switch to the `near` instance of TosContent, this can be done by making our modifications through the `near-discovery-components` repo then changing this entry in the gateway codebase: 
  https://github.com/near/near-discovery/blob/53d909d35bf7dc4162b62ea55073472abee4d933/src/data/bos-components.ts#L139
- since the instance of `TosContent` under the `near` account is not being used, it can currently be freely modified without worrying about prompting users. It is highly important that everything is double checked before rolling out the gateway change to point to that instance, because that is what will trigger the new prompt and if and mistake causes another change to be necessary then we will be spamming users
- currently, I am using a personal Infura account for the IPFS hosting. I can do an upload of the documents if need be but this would also be a good time to spin up a new Infura account not attached to any of our personal email addresses and have those shared credentials available in 1Password. If this is done, it will also require swapping out the IPFS domain for a new address since the one currently used is a dedicated gateway for my account
  - https://github.com/near/near-discovery-components/blob/49988871b82cd480e31497fdc583c144cad8417f/src/TosContent.jsx#L16
![Screenshot 2023-10-05 at 11 07 49 AM](https://github.com/near/near-discovery/assets/24904709/1c2a6152-13e5-4453-984d-88d2b05abd39)
- unfortunately, updating these documents can require quite a bit of tedium if they are not in markdown format. Ideally, it would be great to have them start being maintained in markdown at their source. My process was as follows
  1. Download from Google Docs in `.docx` format
  2. Use the `pandoc` CLI to convert from `.docx` to markdown, I believe this is the command I was using, with `terms.docx` being the downloaded file and `terms.md` being a new file that will be generated by the command
    ```
    pandoc -f docx -t markdown_strict terms.docx -o terms.md
    ```
  3. Manually go through the whole document and fix anything that did not convert cleanly. If I recall correctly, headers were the main thing that did not translate well and needed to be adjusted by hand

**Comment by shelegdmitriy** [comment]
@mpeterdev thanks for such a great description here! I can deal with converting both docs (terms and privacy) to markdown. Could you please help me and to spin up a new Infura account? Or I'll do this next after converting docs

**Comment by mpeterdev** [comment]
@tidus974 @charleslavon Spinning up a new infura account should be trivial once we have a shared email account to use. Do either of you have credentials for one that should be shared? If not, @shelegdmitriy you may need to create a ticket with IT to get one generated

**Comment by charleslavon** [comment]
@shelegdmitriy you can use our existing group email devconsole-team@pagoda.co

**Comment by shelegdmitriy** [comment]
@mpeterdev I created a new infura account. All the credentials are stored in 1Password
