### ISSUE TITLE
Add iOS 16.4+ note to push toast and settings message

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#667]
Hey Illia, we've included this information in the <https://near.org/blog/announcing-web-push-notifications-on-b-o-s|NF blog post>. But to make it more visible I think we could also maybe add this to the gateway itself

<@U01SG6UR5MX> Can we add additional copy to the opt-in modal screens (image below)? We can also surface this on the notification settings page

"Browser push notifications are supported on iOS 16.4 or greater"

cc <@U03EG00RMPB>

[Slack Message](https://pagodaplatform.slack.com/archives/C05N3B7F0G1/p1696531305825999?thread_ts=1696465682.289259&cid=C05N3B7F0G1)

**Comment by ravigautham** [comment]
@shelegdmitriy 

We need to give users more context about how they can enable browser push notifications on mobile.

We should add additional copy to the following screens:

Copy: "Mobile browser push notifications are only supported on iOS 16.4 or greater."

Screens to add copy:
- Notifications Opt-in Modal 
- Notifications Tab Opt-In Component
- Notifications Settings Screen

On the Notification Settings Screen, we should also add the following sentence:

"In order to enable Mobile Browser notifications on iOS, you will also need to add near.org as a icon to your home screen. Click on the share icon, and then tap on "Add to Home Screen""
