### ISSUE TITLE
test.near.org: Unable to accept Terms of Service w/ FastAuth

### ISSUE THREAD

**Issue by Patrick1904** [near/near-discovery#726]
Tried signing up with FastAuth but not able to accept ToS after creating the account. Infinite loading state.

<img width="1338" alt="Screen Shot 2023-10-18 at 3 12 21 PM" src="https://github.com/near/near-discovery/assets/24921205/338f147e-230f-4f4a-9a86-10ec13cb598b">

**Comment by DavidM-D** [comment]
Is the TOS on our side of the fence? Happy to have someone look at it, but isn't it discovery code?

**Comment by charleslavon** [comment]
@DavidM-D Thanks, I think this root cause is on your side. It looks like updating the testnet relayer to use HTTPs should get us closer towards a solution. 

`_app-46f9ca729aa89eb9.js:6 Mixed Content: The page at 'https://test.near.org/' was loaded over HTTPS, but requested an insecure resource 'http://34.70.226.83:3030/relay'. This request has been blocked; the content must be served over HTTPS.`

<img width="1160" alt="Screen Shot 2023-10-31 at 5 14 53 PM" src="https://github.com/near/near-discovery/assets/1915116/d36fc97c-ae77-4496-bec0-82f9e4b477aa">

**Comment by calebjacob** [comment]
Hey @DavidM-D @charleslavon, I was suggesting having someone on the FastAuth team look into this since I can't even sign in at all on `testnet`. When I go to test.near.org and sign in with `caleb@near.org`, I go through the steps and get a confirmation email. When I click the email redirect URL, I always end up on this route:

```
https://test.near.org/signin?code=undefined&reason=%5B-32700%5D+Parse+error%3A+Failed+parsing+args%3A+missing+field+%60account_id%60
```

Maybe I've found an edge case with just my account, but to me it seemed like FastAuth wasn't working at all on `testnet` - not just a ToS issue.

**Comment by MatejVukosav** [comment]
For me, sign-in does not work on testnet. I have switched to the mainnet and it is working. But we should have a working testnet as well.
